let arabicKeywords = [
  "شركة تغليف اثاث",
  "نقل عفش وتركيب",
  "تغليف ونقل الاثاث",
  "فك اثاث",
  "تغليف اثاث",
  "سيارة نقل عفش صغيرة حراج",
  "نقل كنب",
  "فك ونقل اثاث",
  "عربيه نقل العفش",
  "نقل عفش مع تغليف",
  "شركه لنقل العفش",
  "نقل وتغليف اثاث",
  "تغليف العفش",
  "شحن العفش",
  "نقل وتغليف الاثاث",
  "رقم شركة نقل عفش",
  "افضل نقل عفش",
  "فك وتركيب العفش",
  "أفضل شركة نقل عفش",
  "نقل العفش",
  "نقل اثاث",
  "شركة نقل اثاث",
  "دباب نقل عفش",
  "سيارة نقل عفش",
  "شركة منقول لنقل الاثاث",
  "شركة نقل أثاث بالرياض",
  "نقل عفش داخل الرياض",
  "نقل عفش بين المدن",
  "تغليف ونقل الأثاث",
  "فك وتركيب العفش",
  "شحن عفش",
  "شركة نقل أثاث السعودية",
  "نقل العفش مع التغليف",
  "سيارة نقل عفش بالرياض",
  "أفضل شركة نقل عفش",
  "شركة تخزين اثاث بالرياض",
];

const englishKeywords = [
  "Jeddah Furniture Shipping",
  "Furniture Movers Jeddah",
  "Furniture Relocation Jeddah",
  "Moving Furniture Jeddah",
  "Professional Furniture Movers Jeddah",
  "Furniture Packing Jeddah",
  "Local Furniture Movers Jeddah",
  "Long Distance Furniture Moving Jeddah",
  "Furniture Shipping Company Jeddah",
  "Office Furniture Movers Jeddah",
  "Furniture Delivery Services Jeddah",
  "Affordable Furniture Movers Jeddah",
  "Secure Furniture Shipping Jeddah",
  "Furniture Transportation Jeddah",
  "Eyad Movers and Packers",
  "Reliable Furniture Moving Jeddah",
  "Furniture Disassembly and Reassembly Jeddah",
  "Quick Furniture Shipping Jeddah",
  "Furniture Movers Riyadh",
  "Riyadh Furniture Shipping",
  "Furniture Packing Riyadh",
  "Professional Movers Saudi Arabia",
  "Furniture Disassembly and Reassembly",
  "Riyadh Furniture Transport Company",
  "Secure Furniture Moving Riyadh",
  "Affordable Furniture Movers Riyadh",
];

export default [...arabicKeywords, ...englishKeywords];
